app:
  kafka:
    consumer-topic: test
---
spring:
#  config:
#    additional-location: app-config.properties

  datasource:
    url:      ${db.url:localhost:5432}
    username: ${db.username:farid}
    password: ${db.password:farid}
    driver-class-name: ${db.jdbc-driver-class-name:org.postgresql.Driver}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: ${db.jdbc-url:jdbc:postgresql://localhost:5432/farid?currentSchema=bestcommerce}
      schema:   ${db.schema:bestcommerce}
      connection-timeout: ${db.connection-timeout:2000}
      maximum-pool-size: ${db.pool-size:5}

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: merchant
      bootstrap-servers: localhost:9092
